---
extends:
  - "eslint-config-airbnb"

env:
  es6: true
  browser: true
  jest: true

parser: babel-eslint

parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    jsx: true
    classes: true

rules:
  react/jsx-filename-extension:
    - error
    - extensions:
        - ".js"

  global-require: off

  import/no-unresolved: off
